// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SustainMLServiceClient.cxx
 * Client implementation for interfaces
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "SustainMLServiceClient.hpp"

#include <atomic>
#include <exception>
#include <future>
#include <map>
#include <memory>
#include <mutex>
#include <queue>
#include <stdexcept>
#include <string>
#include <thread>

#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/domain/qos/RequesterQos.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/rpc/exceptions.hpp>
#include <fastdds/dds/rpc/interfaces.hpp>
#include <fastdds/dds/rpc/RequestInfo.hpp>
#include <fastdds/dds/rpc/Requester.hpp>
#include <fastdds/dds/rpc/Service.hpp>
#include <fastdds/dds/rpc/ServiceTypeSupport.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/rtps/common/Guid.hpp>
#include <fastdds/rtps/common/WriteParams.hpp>

#include "SustainMLService.hpp"
#include "SustainMLService_details.hpp"
#include "SustainMLServicePubSubTypes.hpp"

//{ interface AppRequirementsService

namespace detail {

namespace fdds = eprosima::fastdds::dds;
namespace frpc = eprosima::fastdds::dds::rpc;
namespace frtps = eprosima::fastdds::rtps;

class AppRequirementsServiceClient : public AppRequirementsService
{

    using RequestType = AppRequirementsService_Request;
    using ReplyType = AppRequirementsService_Reply;

public:

    AppRequirementsServiceClient(
            fdds::DomainParticipant& part,
            const char* service_name,
            const fdds::RequesterQos& qos)
        : AppRequirementsService()
        , participant_(part)
    {
        // Register the service type support
        auto service_type = create_AppRequirementsService_service_type_support();
        auto ret = service_type.register_service_type(&participant_, "AppRequirementsService");
        if (ret != fdds::RETCODE_OK)
        {
            throw std::runtime_error("Error registering service type");
        }

        // Create the service
        service_ = participant_.create_service(service_name, "AppRequirementsService");
        if (nullptr == service_)
        {
            throw std::runtime_error("Error creating service");
        }

        // Create the requester
        requester_ = participant_.create_service_requester(service_, qos);
        if (nullptr == requester_)
        {
            throw std::runtime_error("Error creating requester");
        }

        // Start the processing thread
        start_thread();
    }

    ~AppRequirementsServiceClient() override
    {
        // Stop the processing thread
        stop_thread();

        // Destroy the requester
        if (nullptr != requester_)
        {
            participant_.delete_service_requester(service_->get_service_name(), requester_);
            requester_ = nullptr;
        }

        // Destroy the service
        if (nullptr != service_)
        {
            participant_.delete_service(service_);
            service_ = nullptr;
        }
    }

private:

    void start_thread()
    {
        stop_thread_ = false;
        processing_thread_ = std::thread(&AppRequirementsServiceClient::run, this);
    }

    void stop_thread()
    {
        stop_thread_ = true;
        if (processing_thread_.joinable())
        {
            processing_thread_.join();
        }
    }

    void run()
    {
        while (!stop_thread_)
        {
            // Wait for a reply
            if (requester_->get_requester_reader()->wait_for_unread_message({ 0, 100000000 }))
            {
                // Take and process the reply
                frpc::RequestInfo req_info;
                ReplyType reply;
                auto ret = requester_->take_reply(&reply, req_info);
                if (ret == fdds::RETCODE_OK)
                {
                    process_reply(reply, req_info);
                }
            }
        }
    }

    void process_reply(
            const ReplyType& reply,
            const frpc::RequestInfo& req_info)
    {
        auto sample_id = req_info.related_sample_identity;
        {
            std::lock_guard<std::mutex> _(mtx_);
            auto it = pending_results_.find(sample_id);
            if (it != pending_results_.end())
            {
                bool should_erase = false;
                it->second->process_reply(reply, req_info, should_erase);
                if (should_erase)
                {
                    pending_results_.erase(it);
                }
            }
        }
    }

    struct IReplyProcessor
    {
        frpc::RequestInfo info;

        virtual ~IReplyProcessor() = default;

        virtual void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) = 0;

    };

    fdds::DomainParticipant& participant_;
    frpc::Service* service_ = nullptr;
    frpc::Requester* requester_ = nullptr;
    std::atomic<bool> stop_thread_{false};
    std::thread processing_thread_;
    std::mutex mtx_;
    std::map<frtps::SampleIdentity, std::shared_ptr<IReplyProcessor>> pending_results_;

    //{ request helpers

    template<typename T, typename TResult>
    std::future<TResult> send_request_with_promise(
            const RequestType& request,
            std::shared_ptr<T> result,
            std::promise<TResult>& promise)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            promise.set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return promise.get_future();
    }

    template<typename T>
    std::shared_ptr<T> send_request_with_reader(
            const RequestType& request,
            std::shared_ptr<T> result)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            result->set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return result;
    }

    //} request helpers

    //{ reply helpers

    template<typename T>
    static void set_invalid_reply(
            T& exception_receiver)
    {
        exception_receiver.set_exception(
            std::make_exception_ptr(frpc::RemoteInvalidArgumentError("An invalid reply was received")));
    }

    template<typename T>
    static void set_remote_exception(
            T& exception_receiver,
            const frpc::RemoteExceptionCode_t& exception)
    {
        switch (exception)
        {
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OK:
                set_invalid_reply(exception_receiver);
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNSUPPORTED:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnsupportedError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_INVALID_ARGUMENT:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteInvalidArgumentError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OUT_OF_RESOURCES:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteOutOfResourcesError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNKNOWN_OPERATION:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownOperationError()));
                break;
            default: // REMOTE_EX_UNKNOWN_EXCEPTION
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownExceptionError()));
                break;
        }
    }

    static size_t count_reply_fields(
            const ReplyType& reply)
    {
        size_t n_fields = 0;
        n_fields += reply.update_configuration.has_value() ? 1 : 0;
        n_fields += reply.send_data.has_value() ? 1 : 0;
        n_fields += reply.remoteEx.has_value() ? 1 : 0;
        return n_fields;
    }

    template<typename T>
    static bool validate_reply(
            std::promise<T>& promise,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(promise);
            return false;
        }

        return true;
    }

    struct IExceptionHolder
    {
        virtual ~IExceptionHolder() = default;

        virtual void set_exception(
                std::exception_ptr exception) = 0;
    };

    static bool validate_reply(
            IExceptionHolder& reader,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(reader);
            return false;
        }
        return true;
    }

    //} reply helpers

    //{ operation update_configuration

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> update_configuration(
            /*in*/ const std::string& configuration) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<update_configuration_promise>();

        // Create and send the request
        RequestType request;
        request.update_configuration = detail::AppRequirementsService_update_configuration_In{};
        request.update_configuration->configuration = configuration;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct update_configuration_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.update_configuration.has_value())
            {
                const auto& result = reply.update_configuration.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation update_configuration
 
    //{ operation send_data

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> send_data(
            /*in*/ const std::string& data) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<send_data_promise>();

        // Create and send the request
        RequestType request;
        request.send_data = detail::AppRequirementsService_send_data_In{};
        request.send_data->data = data;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct send_data_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.send_data.has_value())
            {
                const auto& result = reply.send_data.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation send_data
 

};

}  // namespace detail

std::shared_ptr<AppRequirementsService> create_AppRequirementsServiceClient(
        eprosima::fastdds::dds::DomainParticipant& part,
        const char* service_name,
        const eprosima::fastdds::dds::RequesterQos& qos)
{
    return std::make_shared<detail::AppRequirementsServiceClient>(part, service_name, qos);
}

//} interface AppRequirementsServiceClient

//{ interface HWConstraintsService

namespace detail {

namespace fdds = eprosima::fastdds::dds;
namespace frpc = eprosima::fastdds::dds::rpc;
namespace frtps = eprosima::fastdds::rtps;

class HWConstraintsServiceClient : public HWConstraintsService
{

    using RequestType = HWConstraintsService_Request;
    using ReplyType = HWConstraintsService_Reply;

public:

    HWConstraintsServiceClient(
            fdds::DomainParticipant& part,
            const char* service_name,
            const fdds::RequesterQos& qos)
        : HWConstraintsService()
        , participant_(part)
    {
        // Register the service type support
        auto service_type = create_HWConstraintsService_service_type_support();
        auto ret = service_type.register_service_type(&participant_, "HWConstraintsService");
        if (ret != fdds::RETCODE_OK)
        {
            throw std::runtime_error("Error registering service type");
        }

        // Create the service
        service_ = participant_.create_service(service_name, "HWConstraintsService");
        if (nullptr == service_)
        {
            throw std::runtime_error("Error creating service");
        }

        // Create the requester
        requester_ = participant_.create_service_requester(service_, qos);
        if (nullptr == requester_)
        {
            throw std::runtime_error("Error creating requester");
        }

        // Start the processing thread
        start_thread();
    }

    ~HWConstraintsServiceClient() override
    {
        // Stop the processing thread
        stop_thread();

        // Destroy the requester
        if (nullptr != requester_)
        {
            participant_.delete_service_requester(service_->get_service_name(), requester_);
            requester_ = nullptr;
        }

        // Destroy the service
        if (nullptr != service_)
        {
            participant_.delete_service(service_);
            service_ = nullptr;
        }
    }

private:

    void start_thread()
    {
        stop_thread_ = false;
        processing_thread_ = std::thread(&HWConstraintsServiceClient::run, this);
    }

    void stop_thread()
    {
        stop_thread_ = true;
        if (processing_thread_.joinable())
        {
            processing_thread_.join();
        }
    }

    void run()
    {
        while (!stop_thread_)
        {
            // Wait for a reply
            if (requester_->get_requester_reader()->wait_for_unread_message({ 0, 100000000 }))
            {
                // Take and process the reply
                frpc::RequestInfo req_info;
                ReplyType reply;
                auto ret = requester_->take_reply(&reply, req_info);
                if (ret == fdds::RETCODE_OK)
                {
                    process_reply(reply, req_info);
                }
            }
        }
    }

    void process_reply(
            const ReplyType& reply,
            const frpc::RequestInfo& req_info)
    {
        auto sample_id = req_info.related_sample_identity;
        {
            std::lock_guard<std::mutex> _(mtx_);
            auto it = pending_results_.find(sample_id);
            if (it != pending_results_.end())
            {
                bool should_erase = false;
                it->second->process_reply(reply, req_info, should_erase);
                if (should_erase)
                {
                    pending_results_.erase(it);
                }
            }
        }
    }

    struct IReplyProcessor
    {
        frpc::RequestInfo info;

        virtual ~IReplyProcessor() = default;

        virtual void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) = 0;

    };

    fdds::DomainParticipant& participant_;
    frpc::Service* service_ = nullptr;
    frpc::Requester* requester_ = nullptr;
    std::atomic<bool> stop_thread_{false};
    std::thread processing_thread_;
    std::mutex mtx_;
    std::map<frtps::SampleIdentity, std::shared_ptr<IReplyProcessor>> pending_results_;

    //{ request helpers

    template<typename T, typename TResult>
    std::future<TResult> send_request_with_promise(
            const RequestType& request,
            std::shared_ptr<T> result,
            std::promise<TResult>& promise)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            promise.set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return promise.get_future();
    }

    template<typename T>
    std::shared_ptr<T> send_request_with_reader(
            const RequestType& request,
            std::shared_ptr<T> result)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            result->set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return result;
    }

    //} request helpers

    //{ reply helpers

    template<typename T>
    static void set_invalid_reply(
            T& exception_receiver)
    {
        exception_receiver.set_exception(
            std::make_exception_ptr(frpc::RemoteInvalidArgumentError("An invalid reply was received")));
    }

    template<typename T>
    static void set_remote_exception(
            T& exception_receiver,
            const frpc::RemoteExceptionCode_t& exception)
    {
        switch (exception)
        {
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OK:
                set_invalid_reply(exception_receiver);
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNSUPPORTED:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnsupportedError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_INVALID_ARGUMENT:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteInvalidArgumentError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OUT_OF_RESOURCES:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteOutOfResourcesError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNKNOWN_OPERATION:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownOperationError()));
                break;
            default: // REMOTE_EX_UNKNOWN_EXCEPTION
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownExceptionError()));
                break;
        }
    }

    static size_t count_reply_fields(
            const ReplyType& reply)
    {
        size_t n_fields = 0;
        n_fields += reply.update_configuration.has_value() ? 1 : 0;
        n_fields += reply.send_data.has_value() ? 1 : 0;
        n_fields += reply.remoteEx.has_value() ? 1 : 0;
        return n_fields;
    }

    template<typename T>
    static bool validate_reply(
            std::promise<T>& promise,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(promise);
            return false;
        }

        return true;
    }

    struct IExceptionHolder
    {
        virtual ~IExceptionHolder() = default;

        virtual void set_exception(
                std::exception_ptr exception) = 0;
    };

    static bool validate_reply(
            IExceptionHolder& reader,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(reader);
            return false;
        }
        return true;
    }

    //} reply helpers

    //{ operation update_configuration

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> update_configuration(
            /*in*/ const std::string& configuration) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<update_configuration_promise>();

        // Create and send the request
        RequestType request;
        request.update_configuration = detail::HWConstraintsService_update_configuration_In{};
        request.update_configuration->configuration = configuration;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct update_configuration_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.update_configuration.has_value())
            {
                const auto& result = reply.update_configuration.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation update_configuration
 
    //{ operation send_data

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> send_data(
            /*in*/ const std::string& data) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<send_data_promise>();

        // Create and send the request
        RequestType request;
        request.send_data = detail::HWConstraintsService_send_data_In{};
        request.send_data->data = data;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct send_data_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.send_data.has_value())
            {
                const auto& result = reply.send_data.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation send_data
 

};

}  // namespace detail

std::shared_ptr<HWConstraintsService> create_HWConstraintsServiceClient(
        eprosima::fastdds::dds::DomainParticipant& part,
        const char* service_name,
        const eprosima::fastdds::dds::RequesterQos& qos)
{
    return std::make_shared<detail::HWConstraintsServiceClient>(part, service_name, qos);
}

//} interface HWConstraintsServiceClient

//{ interface HWResourcesService

namespace detail {

namespace fdds = eprosima::fastdds::dds;
namespace frpc = eprosima::fastdds::dds::rpc;
namespace frtps = eprosima::fastdds::rtps;

class HWResourcesServiceClient : public HWResourcesService
{

    using RequestType = HWResourcesService_Request;
    using ReplyType = HWResourcesService_Reply;

public:

    HWResourcesServiceClient(
            fdds::DomainParticipant& part,
            const char* service_name,
            const fdds::RequesterQos& qos)
        : HWResourcesService()
        , participant_(part)
    {
        // Register the service type support
        auto service_type = create_HWResourcesService_service_type_support();
        auto ret = service_type.register_service_type(&participant_, "HWResourcesService");
        if (ret != fdds::RETCODE_OK)
        {
            throw std::runtime_error("Error registering service type");
        }

        // Create the service
        service_ = participant_.create_service(service_name, "HWResourcesService");
        if (nullptr == service_)
        {
            throw std::runtime_error("Error creating service");
        }

        // Create the requester
        requester_ = participant_.create_service_requester(service_, qos);
        if (nullptr == requester_)
        {
            throw std::runtime_error("Error creating requester");
        }

        // Start the processing thread
        start_thread();
    }

    ~HWResourcesServiceClient() override
    {
        // Stop the processing thread
        stop_thread();

        // Destroy the requester
        if (nullptr != requester_)
        {
            participant_.delete_service_requester(service_->get_service_name(), requester_);
            requester_ = nullptr;
        }

        // Destroy the service
        if (nullptr != service_)
        {
            participant_.delete_service(service_);
            service_ = nullptr;
        }
    }

private:

    void start_thread()
    {
        stop_thread_ = false;
        processing_thread_ = std::thread(&HWResourcesServiceClient::run, this);
    }

    void stop_thread()
    {
        stop_thread_ = true;
        if (processing_thread_.joinable())
        {
            processing_thread_.join();
        }
    }

    void run()
    {
        while (!stop_thread_)
        {
            // Wait for a reply
            if (requester_->get_requester_reader()->wait_for_unread_message({ 0, 100000000 }))
            {
                // Take and process the reply
                frpc::RequestInfo req_info;
                ReplyType reply;
                auto ret = requester_->take_reply(&reply, req_info);
                if (ret == fdds::RETCODE_OK)
                {
                    process_reply(reply, req_info);
                }
            }
        }
    }

    void process_reply(
            const ReplyType& reply,
            const frpc::RequestInfo& req_info)
    {
        auto sample_id = req_info.related_sample_identity;
        {
            std::lock_guard<std::mutex> _(mtx_);
            auto it = pending_results_.find(sample_id);
            if (it != pending_results_.end())
            {
                bool should_erase = false;
                it->second->process_reply(reply, req_info, should_erase);
                if (should_erase)
                {
                    pending_results_.erase(it);
                }
            }
        }
    }

    struct IReplyProcessor
    {
        frpc::RequestInfo info;

        virtual ~IReplyProcessor() = default;

        virtual void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) = 0;

    };

    fdds::DomainParticipant& participant_;
    frpc::Service* service_ = nullptr;
    frpc::Requester* requester_ = nullptr;
    std::atomic<bool> stop_thread_{false};
    std::thread processing_thread_;
    std::mutex mtx_;
    std::map<frtps::SampleIdentity, std::shared_ptr<IReplyProcessor>> pending_results_;

    //{ request helpers

    template<typename T, typename TResult>
    std::future<TResult> send_request_with_promise(
            const RequestType& request,
            std::shared_ptr<T> result,
            std::promise<TResult>& promise)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            promise.set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return promise.get_future();
    }

    template<typename T>
    std::shared_ptr<T> send_request_with_reader(
            const RequestType& request,
            std::shared_ptr<T> result)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            result->set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return result;
    }

    //} request helpers

    //{ reply helpers

    template<typename T>
    static void set_invalid_reply(
            T& exception_receiver)
    {
        exception_receiver.set_exception(
            std::make_exception_ptr(frpc::RemoteInvalidArgumentError("An invalid reply was received")));
    }

    template<typename T>
    static void set_remote_exception(
            T& exception_receiver,
            const frpc::RemoteExceptionCode_t& exception)
    {
        switch (exception)
        {
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OK:
                set_invalid_reply(exception_receiver);
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNSUPPORTED:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnsupportedError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_INVALID_ARGUMENT:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteInvalidArgumentError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OUT_OF_RESOURCES:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteOutOfResourcesError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNKNOWN_OPERATION:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownOperationError()));
                break;
            default: // REMOTE_EX_UNKNOWN_EXCEPTION
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownExceptionError()));
                break;
        }
    }

    static size_t count_reply_fields(
            const ReplyType& reply)
    {
        size_t n_fields = 0;
        n_fields += reply.update_configuration.has_value() ? 1 : 0;
        n_fields += reply.send_data.has_value() ? 1 : 0;
        n_fields += reply.remoteEx.has_value() ? 1 : 0;
        return n_fields;
    }

    template<typename T>
    static bool validate_reply(
            std::promise<T>& promise,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(promise);
            return false;
        }

        return true;
    }

    struct IExceptionHolder
    {
        virtual ~IExceptionHolder() = default;

        virtual void set_exception(
                std::exception_ptr exception) = 0;
    };

    static bool validate_reply(
            IExceptionHolder& reader,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(reader);
            return false;
        }
        return true;
    }

    //} reply helpers

    //{ operation update_configuration

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> update_configuration(
            /*in*/ const std::string& configuration) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<update_configuration_promise>();

        // Create and send the request
        RequestType request;
        request.update_configuration = detail::HWResourcesService_update_configuration_In{};
        request.update_configuration->configuration = configuration;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct update_configuration_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.update_configuration.has_value())
            {
                const auto& result = reply.update_configuration.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation update_configuration
 
    //{ operation send_data

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> send_data(
            /*in*/ const std::string& data) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<send_data_promise>();

        // Create and send the request
        RequestType request;
        request.send_data = detail::HWResourcesService_send_data_In{};
        request.send_data->data = data;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct send_data_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.send_data.has_value())
            {
                const auto& result = reply.send_data.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation send_data
 

};

}  // namespace detail

std::shared_ptr<HWResourcesService> create_HWResourcesServiceClient(
        eprosima::fastdds::dds::DomainParticipant& part,
        const char* service_name,
        const eprosima::fastdds::dds::RequesterQos& qos)
{
    return std::make_shared<detail::HWResourcesServiceClient>(part, service_name, qos);
}

//} interface HWResourcesServiceClient

//{ interface CarbonFootprintService

namespace detail {

namespace fdds = eprosima::fastdds::dds;
namespace frpc = eprosima::fastdds::dds::rpc;
namespace frtps = eprosima::fastdds::rtps;

class CarbonFootprintServiceClient : public CarbonFootprintService
{

    using RequestType = CarbonFootprintService_Request;
    using ReplyType = CarbonFootprintService_Reply;

public:

    CarbonFootprintServiceClient(
            fdds::DomainParticipant& part,
            const char* service_name,
            const fdds::RequesterQos& qos)
        : CarbonFootprintService()
        , participant_(part)
    {
        // Register the service type support
        auto service_type = create_CarbonFootprintService_service_type_support();
        auto ret = service_type.register_service_type(&participant_, "CarbonFootprintService");
        if (ret != fdds::RETCODE_OK)
        {
            throw std::runtime_error("Error registering service type");
        }

        // Create the service
        service_ = participant_.create_service(service_name, "CarbonFootprintService");
        if (nullptr == service_)
        {
            throw std::runtime_error("Error creating service");
        }

        // Create the requester
        requester_ = participant_.create_service_requester(service_, qos);
        if (nullptr == requester_)
        {
            throw std::runtime_error("Error creating requester");
        }

        // Start the processing thread
        start_thread();
    }

    ~CarbonFootprintServiceClient() override
    {
        // Stop the processing thread
        stop_thread();

        // Destroy the requester
        if (nullptr != requester_)
        {
            participant_.delete_service_requester(service_->get_service_name(), requester_);
            requester_ = nullptr;
        }

        // Destroy the service
        if (nullptr != service_)
        {
            participant_.delete_service(service_);
            service_ = nullptr;
        }
    }

private:

    void start_thread()
    {
        stop_thread_ = false;
        processing_thread_ = std::thread(&CarbonFootprintServiceClient::run, this);
    }

    void stop_thread()
    {
        stop_thread_ = true;
        if (processing_thread_.joinable())
        {
            processing_thread_.join();
        }
    }

    void run()
    {
        while (!stop_thread_)
        {
            // Wait for a reply
            if (requester_->get_requester_reader()->wait_for_unread_message({ 0, 100000000 }))
            {
                // Take and process the reply
                frpc::RequestInfo req_info;
                ReplyType reply;
                auto ret = requester_->take_reply(&reply, req_info);
                if (ret == fdds::RETCODE_OK)
                {
                    process_reply(reply, req_info);
                }
            }
        }
    }

    void process_reply(
            const ReplyType& reply,
            const frpc::RequestInfo& req_info)
    {
        auto sample_id = req_info.related_sample_identity;
        {
            std::lock_guard<std::mutex> _(mtx_);
            auto it = pending_results_.find(sample_id);
            if (it != pending_results_.end())
            {
                bool should_erase = false;
                it->second->process_reply(reply, req_info, should_erase);
                if (should_erase)
                {
                    pending_results_.erase(it);
                }
            }
        }
    }

    struct IReplyProcessor
    {
        frpc::RequestInfo info;

        virtual ~IReplyProcessor() = default;

        virtual void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) = 0;

    };

    fdds::DomainParticipant& participant_;
    frpc::Service* service_ = nullptr;
    frpc::Requester* requester_ = nullptr;
    std::atomic<bool> stop_thread_{false};
    std::thread processing_thread_;
    std::mutex mtx_;
    std::map<frtps::SampleIdentity, std::shared_ptr<IReplyProcessor>> pending_results_;

    //{ request helpers

    template<typename T, typename TResult>
    std::future<TResult> send_request_with_promise(
            const RequestType& request,
            std::shared_ptr<T> result,
            std::promise<TResult>& promise)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            promise.set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return promise.get_future();
    }

    template<typename T>
    std::shared_ptr<T> send_request_with_reader(
            const RequestType& request,
            std::shared_ptr<T> result)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            result->set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return result;
    }

    //} request helpers

    //{ reply helpers

    template<typename T>
    static void set_invalid_reply(
            T& exception_receiver)
    {
        exception_receiver.set_exception(
            std::make_exception_ptr(frpc::RemoteInvalidArgumentError("An invalid reply was received")));
    }

    template<typename T>
    static void set_remote_exception(
            T& exception_receiver,
            const frpc::RemoteExceptionCode_t& exception)
    {
        switch (exception)
        {
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OK:
                set_invalid_reply(exception_receiver);
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNSUPPORTED:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnsupportedError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_INVALID_ARGUMENT:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteInvalidArgumentError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OUT_OF_RESOURCES:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteOutOfResourcesError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNKNOWN_OPERATION:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownOperationError()));
                break;
            default: // REMOTE_EX_UNKNOWN_EXCEPTION
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownExceptionError()));
                break;
        }
    }

    static size_t count_reply_fields(
            const ReplyType& reply)
    {
        size_t n_fields = 0;
        n_fields += reply.update_configuration.has_value() ? 1 : 0;
        n_fields += reply.send_data.has_value() ? 1 : 0;
        n_fields += reply.remoteEx.has_value() ? 1 : 0;
        return n_fields;
    }

    template<typename T>
    static bool validate_reply(
            std::promise<T>& promise,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(promise);
            return false;
        }

        return true;
    }

    struct IExceptionHolder
    {
        virtual ~IExceptionHolder() = default;

        virtual void set_exception(
                std::exception_ptr exception) = 0;
    };

    static bool validate_reply(
            IExceptionHolder& reader,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(reader);
            return false;
        }
        return true;
    }

    //} reply helpers

    //{ operation update_configuration

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> update_configuration(
            /*in*/ const std::string& configuration) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<update_configuration_promise>();

        // Create and send the request
        RequestType request;
        request.update_configuration = detail::CarbonFootprintService_update_configuration_In{};
        request.update_configuration->configuration = configuration;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct update_configuration_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.update_configuration.has_value())
            {
                const auto& result = reply.update_configuration.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation update_configuration
 
    //{ operation send_data

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> send_data(
            /*in*/ const std::string& data) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<send_data_promise>();

        // Create and send the request
        RequestType request;
        request.send_data = detail::CarbonFootprintService_send_data_In{};
        request.send_data->data = data;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct send_data_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.send_data.has_value())
            {
                const auto& result = reply.send_data.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation send_data
 

};

}  // namespace detail

std::shared_ptr<CarbonFootprintService> create_CarbonFootprintServiceClient(
        eprosima::fastdds::dds::DomainParticipant& part,
        const char* service_name,
        const eprosima::fastdds::dds::RequesterQos& qos)
{
    return std::make_shared<detail::CarbonFootprintServiceClient>(part, service_name, qos);
}

//} interface CarbonFootprintServiceClient

//{ interface MLModelMetadataService

namespace detail {

namespace fdds = eprosima::fastdds::dds;
namespace frpc = eprosima::fastdds::dds::rpc;
namespace frtps = eprosima::fastdds::rtps;

class MLModelMetadataServiceClient : public MLModelMetadataService
{

    using RequestType = MLModelMetadataService_Request;
    using ReplyType = MLModelMetadataService_Reply;

public:

    MLModelMetadataServiceClient(
            fdds::DomainParticipant& part,
            const char* service_name,
            const fdds::RequesterQos& qos)
        : MLModelMetadataService()
        , participant_(part)
    {
        // Register the service type support
        auto service_type = create_MLModelMetadataService_service_type_support();
        auto ret = service_type.register_service_type(&participant_, "MLModelMetadataService");
        if (ret != fdds::RETCODE_OK)
        {
            throw std::runtime_error("Error registering service type");
        }

        // Create the service
        service_ = participant_.create_service(service_name, "MLModelMetadataService");
        if (nullptr == service_)
        {
            throw std::runtime_error("Error creating service");
        }

        // Create the requester
        requester_ = participant_.create_service_requester(service_, qos);
        if (nullptr == requester_)
        {
            throw std::runtime_error("Error creating requester");
        }

        // Start the processing thread
        start_thread();
    }

    ~MLModelMetadataServiceClient() override
    {
        // Stop the processing thread
        stop_thread();

        // Destroy the requester
        if (nullptr != requester_)
        {
            participant_.delete_service_requester(service_->get_service_name(), requester_);
            requester_ = nullptr;
        }

        // Destroy the service
        if (nullptr != service_)
        {
            participant_.delete_service(service_);
            service_ = nullptr;
        }
    }

private:

    void start_thread()
    {
        stop_thread_ = false;
        processing_thread_ = std::thread(&MLModelMetadataServiceClient::run, this);
    }

    void stop_thread()
    {
        stop_thread_ = true;
        if (processing_thread_.joinable())
        {
            processing_thread_.join();
        }
    }

    void run()
    {
        while (!stop_thread_)
        {
            // Wait for a reply
            if (requester_->get_requester_reader()->wait_for_unread_message({ 0, 100000000 }))
            {
                // Take and process the reply
                frpc::RequestInfo req_info;
                ReplyType reply;
                auto ret = requester_->take_reply(&reply, req_info);
                if (ret == fdds::RETCODE_OK)
                {
                    process_reply(reply, req_info);
                }
            }
        }
    }

    void process_reply(
            const ReplyType& reply,
            const frpc::RequestInfo& req_info)
    {
        auto sample_id = req_info.related_sample_identity;
        {
            std::lock_guard<std::mutex> _(mtx_);
            auto it = pending_results_.find(sample_id);
            if (it != pending_results_.end())
            {
                bool should_erase = false;
                it->second->process_reply(reply, req_info, should_erase);
                if (should_erase)
                {
                    pending_results_.erase(it);
                }
            }
        }
    }

    struct IReplyProcessor
    {
        frpc::RequestInfo info;

        virtual ~IReplyProcessor() = default;

        virtual void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) = 0;

    };

    fdds::DomainParticipant& participant_;
    frpc::Service* service_ = nullptr;
    frpc::Requester* requester_ = nullptr;
    std::atomic<bool> stop_thread_{false};
    std::thread processing_thread_;
    std::mutex mtx_;
    std::map<frtps::SampleIdentity, std::shared_ptr<IReplyProcessor>> pending_results_;

    //{ request helpers

    template<typename T, typename TResult>
    std::future<TResult> send_request_with_promise(
            const RequestType& request,
            std::shared_ptr<T> result,
            std::promise<TResult>& promise)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            promise.set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return promise.get_future();
    }

    template<typename T>
    std::shared_ptr<T> send_request_with_reader(
            const RequestType& request,
            std::shared_ptr<T> result)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            result->set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return result;
    }

    //} request helpers

    //{ reply helpers

    template<typename T>
    static void set_invalid_reply(
            T& exception_receiver)
    {
        exception_receiver.set_exception(
            std::make_exception_ptr(frpc::RemoteInvalidArgumentError("An invalid reply was received")));
    }

    template<typename T>
    static void set_remote_exception(
            T& exception_receiver,
            const frpc::RemoteExceptionCode_t& exception)
    {
        switch (exception)
        {
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OK:
                set_invalid_reply(exception_receiver);
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNSUPPORTED:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnsupportedError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_INVALID_ARGUMENT:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteInvalidArgumentError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OUT_OF_RESOURCES:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteOutOfResourcesError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNKNOWN_OPERATION:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownOperationError()));
                break;
            default: // REMOTE_EX_UNKNOWN_EXCEPTION
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownExceptionError()));
                break;
        }
    }

    static size_t count_reply_fields(
            const ReplyType& reply)
    {
        size_t n_fields = 0;
        n_fields += reply.update_configuration.has_value() ? 1 : 0;
        n_fields += reply.send_data.has_value() ? 1 : 0;
        n_fields += reply.remoteEx.has_value() ? 1 : 0;
        return n_fields;
    }

    template<typename T>
    static bool validate_reply(
            std::promise<T>& promise,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(promise);
            return false;
        }

        return true;
    }

    struct IExceptionHolder
    {
        virtual ~IExceptionHolder() = default;

        virtual void set_exception(
                std::exception_ptr exception) = 0;
    };

    static bool validate_reply(
            IExceptionHolder& reader,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(reader);
            return false;
        }
        return true;
    }

    //} reply helpers

    //{ operation update_configuration

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> update_configuration(
            /*in*/ const std::string& configuration) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<update_configuration_promise>();

        // Create and send the request
        RequestType request;
        request.update_configuration = detail::MLModelMetadataService_update_configuration_In{};
        request.update_configuration->configuration = configuration;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct update_configuration_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.update_configuration.has_value())
            {
                const auto& result = reply.update_configuration.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation update_configuration
 
    //{ operation send_data

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> send_data(
            /*in*/ const std::string& data) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<send_data_promise>();

        // Create and send the request
        RequestType request;
        request.send_data = detail::MLModelMetadataService_send_data_In{};
        request.send_data->data = data;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct send_data_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.send_data.has_value())
            {
                const auto& result = reply.send_data.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation send_data
 

};

}  // namespace detail

std::shared_ptr<MLModelMetadataService> create_MLModelMetadataServiceClient(
        eprosima::fastdds::dds::DomainParticipant& part,
        const char* service_name,
        const eprosima::fastdds::dds::RequesterQos& qos)
{
    return std::make_shared<detail::MLModelMetadataServiceClient>(part, service_name, qos);
}

//} interface MLModelMetadataServiceClient

//{ interface MLModelService

namespace detail {

namespace fdds = eprosima::fastdds::dds;
namespace frpc = eprosima::fastdds::dds::rpc;
namespace frtps = eprosima::fastdds::rtps;

class MLModelServiceClient : public MLModelService
{

    using RequestType = MLModelService_Request;
    using ReplyType = MLModelService_Reply;

public:

    MLModelServiceClient(
            fdds::DomainParticipant& part,
            const char* service_name,
            const fdds::RequesterQos& qos)
        : MLModelService()
        , participant_(part)
    {
        // Register the service type support
        auto service_type = create_MLModelService_service_type_support();
        auto ret = service_type.register_service_type(&participant_, "MLModelService");
        if (ret != fdds::RETCODE_OK)
        {
            throw std::runtime_error("Error registering service type");
        }

        // Create the service
        service_ = participant_.create_service(service_name, "MLModelService");
        if (nullptr == service_)
        {
            throw std::runtime_error("Error creating service");
        }

        // Create the requester
        requester_ = participant_.create_service_requester(service_, qos);
        if (nullptr == requester_)
        {
            throw std::runtime_error("Error creating requester");
        }

        // Start the processing thread
        start_thread();
    }

    ~MLModelServiceClient() override
    {
        // Stop the processing thread
        stop_thread();

        // Destroy the requester
        if (nullptr != requester_)
        {
            participant_.delete_service_requester(service_->get_service_name(), requester_);
            requester_ = nullptr;
        }

        // Destroy the service
        if (nullptr != service_)
        {
            participant_.delete_service(service_);
            service_ = nullptr;
        }
    }

private:

    void start_thread()
    {
        stop_thread_ = false;
        processing_thread_ = std::thread(&MLModelServiceClient::run, this);
    }

    void stop_thread()
    {
        stop_thread_ = true;
        if (processing_thread_.joinable())
        {
            processing_thread_.join();
        }
    }

    void run()
    {
        while (!stop_thread_)
        {
            // Wait for a reply
            if (requester_->get_requester_reader()->wait_for_unread_message({ 0, 100000000 }))
            {
                // Take and process the reply
                frpc::RequestInfo req_info;
                ReplyType reply;
                auto ret = requester_->take_reply(&reply, req_info);
                if (ret == fdds::RETCODE_OK)
                {
                    process_reply(reply, req_info);
                }
            }
        }
    }

    void process_reply(
            const ReplyType& reply,
            const frpc::RequestInfo& req_info)
    {
        auto sample_id = req_info.related_sample_identity;
        {
            std::lock_guard<std::mutex> _(mtx_);
            auto it = pending_results_.find(sample_id);
            if (it != pending_results_.end())
            {
                bool should_erase = false;
                it->second->process_reply(reply, req_info, should_erase);
                if (should_erase)
                {
                    pending_results_.erase(it);
                }
            }
        }
    }

    struct IReplyProcessor
    {
        frpc::RequestInfo info;

        virtual ~IReplyProcessor() = default;

        virtual void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) = 0;

    };

    fdds::DomainParticipant& participant_;
    frpc::Service* service_ = nullptr;
    frpc::Requester* requester_ = nullptr;
    std::atomic<bool> stop_thread_{false};
    std::thread processing_thread_;
    std::mutex mtx_;
    std::map<frtps::SampleIdentity, std::shared_ptr<IReplyProcessor>> pending_results_;

    //{ request helpers

    template<typename T, typename TResult>
    std::future<TResult> send_request_with_promise(
            const RequestType& request,
            std::shared_ptr<T> result,
            std::promise<TResult>& promise)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            promise.set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return promise.get_future();
    }

    template<typename T>
    std::shared_ptr<T> send_request_with_reader(
            const RequestType& request,
            std::shared_ptr<T> result)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            result->set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return result;
    }

    //} request helpers

    //{ reply helpers

    template<typename T>
    static void set_invalid_reply(
            T& exception_receiver)
    {
        exception_receiver.set_exception(
            std::make_exception_ptr(frpc::RemoteInvalidArgumentError("An invalid reply was received")));
    }

    template<typename T>
    static void set_remote_exception(
            T& exception_receiver,
            const frpc::RemoteExceptionCode_t& exception)
    {
        switch (exception)
        {
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OK:
                set_invalid_reply(exception_receiver);
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNSUPPORTED:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnsupportedError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_INVALID_ARGUMENT:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteInvalidArgumentError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OUT_OF_RESOURCES:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteOutOfResourcesError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNKNOWN_OPERATION:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownOperationError()));
                break;
            default: // REMOTE_EX_UNKNOWN_EXCEPTION
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownExceptionError()));
                break;
        }
    }

    static size_t count_reply_fields(
            const ReplyType& reply)
    {
        size_t n_fields = 0;
        n_fields += reply.update_configuration.has_value() ? 1 : 0;
        n_fields += reply.send_data.has_value() ? 1 : 0;
        n_fields += reply.remoteEx.has_value() ? 1 : 0;
        return n_fields;
    }

    template<typename T>
    static bool validate_reply(
            std::promise<T>& promise,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(promise);
            return false;
        }

        return true;
    }

    struct IExceptionHolder
    {
        virtual ~IExceptionHolder() = default;

        virtual void set_exception(
                std::exception_ptr exception) = 0;
    };

    static bool validate_reply(
            IExceptionHolder& reader,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(reader);
            return false;
        }
        return true;
    }

    //} reply helpers

    //{ operation update_configuration

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> update_configuration(
            /*in*/ const std::string& configuration) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<update_configuration_promise>();

        // Create and send the request
        RequestType request;
        request.update_configuration = detail::MLModelService_update_configuration_In{};
        request.update_configuration->configuration = configuration;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct update_configuration_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.update_configuration.has_value())
            {
                const auto& result = reply.update_configuration.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation update_configuration
 
    //{ operation send_data

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> send_data(
            /*in*/ const std::string& data) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<send_data_promise>();

        // Create and send the request
        RequestType request;
        request.send_data = detail::MLModelService_send_data_In{};
        request.send_data->data = data;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct send_data_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.send_data.has_value())
            {
                const auto& result = reply.send_data.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
                if (result.InternalError_ex.has_value())
                {
                    promise.set_exception(
                        std::make_exception_ptr(result.InternalError_ex.value()));
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation send_data
 

};

}  // namespace detail

std::shared_ptr<MLModelService> create_MLModelServiceClient(
        eprosima::fastdds::dds::DomainParticipant& part,
        const char* service_name,
        const eprosima::fastdds::dds::RequesterQos& qos)
{
    return std::make_shared<detail::MLModelServiceClient>(part, service_name, qos);
}

//} interface MLModelServiceClient
