// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file typesCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_TYPESCDRAUX_HPP_
#define _FAST_DDS_GENERATED_TYPESCDRAUX_HPP_

#include "types.h"

constexpr uint32_t UserInput_max_cdr_typesize {792UL};
constexpr uint32_t UserInput_max_key_cdr_typesize {4UL};

constexpr uint32_t MLModel_max_cdr_typesize {1048UL};
constexpr uint32_t MLModel_max_key_cdr_typesize {4UL};


constexpr uint32_t EncodedTask_max_cdr_typesize {26016UL};
constexpr uint32_t EncodedTask_max_key_cdr_typesize {4UL};

constexpr uint32_t HWResource_max_cdr_typesize {276UL};
constexpr uint32_t HWResource_max_key_cdr_typesize {4UL};

constexpr uint32_t NodeControl_max_cdr_typesize {536UL};
constexpr uint32_t NodeControl_max_key_cdr_typesize {260UL};




constexpr uint32_t GeoLocation_max_cdr_typesize {524UL};
constexpr uint32_t GeoLocation_max_key_cdr_typesize {0UL};

constexpr uint32_t NodeStatus_max_cdr_typesize {540UL};
constexpr uint32_t NodeStatus_max_key_cdr_typesize {264UL};

constexpr uint32_t CO2Footprint_max_cdr_typesize {36UL};
constexpr uint32_t CO2Footprint_max_key_cdr_typesize {4UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const NodeStatus& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const NodeControl& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const GeoLocation& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const UserInput& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const EncodedTask& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const MLModel& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const HWResource& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const CO2Footprint& data);


} // namespace fastcdr
} // namespace eprosima

#endif // _FAST_DDS_GENERATED_TYPESCDRAUX_HPP_